version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 8200:9200
    # networks:
    #  - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
  web:
    image: httpd:latest
    volumes:
      - semehr_phenome_ui_folder:/usr/local/apache2/htdocs/
    restart: always
    ports:
      - "8080:80"
volumes:
  esdata01:
    driver_opts:
      type: none
      device: /semehr_tutorial1/working_data/docker_es01
      o: bind
  esdata02:
    driver_opts:
      type: none
      device: /semehr_tutorial1/working_data/docker_es02
      o: bind
  semehr_phenome_ui_folder:
    driver_opts:
      type: none
      device: /semehr_tutorial1/Cogstack-SemEHR/UI/patient_phenome_ui
      o: bind
